//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIP_Parking.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public int PermitCode { get; set; }
        public int Reserv_ID { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
